using Kysect.CommonLib.BaseTypes.Extensions;
using Kysect.CommonLib.Collections.Extensions;
using Kysect.Configuin.DotnetConfig.Syntax;
using Kysect.Configuin.DotnetConfig.Syntax.Nodes;
using Kysect.Configuin.RoslynModels;

namespace Kysect.Configuin.DotnetConfig.Formatter;

public class DotnetConfigDocumentFormatter
{
    public DotnetConfigDocument Format(DotnetConfigDocument value)
    {
        List<IDotnetConfigPropertySyntaxNode> nodesForRemoving = new List<IDotnetConfigPropertySyntaxNode>();
        IReadOnlyCollection<IDotnetConfigPropertySyntaxNode> styleRuleNodesForMoving = SelectIdeNodes(value, RoslynRuleTypes.StyleRule).OrderBy(r => r.Key).ToList();
        IReadOnlyCollection<IDotnetConfigPropertySyntaxNode> qualityRuleNodesForMoving = SelectIdeNodes(value, RoslynRuleTypes.QualityRule).OrderBy(r => r.Key).ToList();
        nodesForRemoving.AddRange(styleRuleNodesForMoving);
        nodesForRemoving.AddRange(qualityRuleNodesForMoving);

        if (nodesForRemoving.IsEmpty())
            return value;

        DotnetConfigCategoryNode autoGeneratedSection = CreateAutoGeneratedCategory(styleRuleNodesForMoving, [new RoslynQualityRuleFormattedSection("CA", qualityRuleNodesForMoving)]);

        return value
            .RemoveNodes(nodesForRemoving)
            .AddChild(autoGeneratedSection);
    }

    public DotnetConfigDocument FormatAccordingToRuleDefinitions(DotnetConfigDocument document, RoslynRules rules, bool groupQualityRulesByCategory = false)
    {
        rules.ThrowIfNull();

        List<IDotnetConfigPropertySyntaxNode> nodesForRemoving = new List<IDotnetConfigPropertySyntaxNode>();

        List<IDotnetConfigPropertySyntaxNode> propertyNodes = document
            .DescendantNodes()
            .OfType<IDotnetConfigPropertySyntaxNode>()
            .ToList();

        List<IDotnetConfigPropertySyntaxNode> selectedStyleRuleNodes = new List<IDotnetConfigPropertySyntaxNode>();
        foreach (RoslynStyleRuleGroup roslynStyleRuleGroup in rules.StyleRuleGroups)
        {
            foreach (RoslynStyleRule roslynStyleRule in roslynStyleRuleGroup.Rules)
            {
                IDotnetConfigPropertySyntaxNode? editorConfigPropertyNode = TryFindSeverityNode(propertyNodes, roslynStyleRule.RuleId);
                if (editorConfigPropertyNode is null)
                    continue;

                selectedStyleRuleNodes.Add(editorConfigPropertyNode);
            }

            foreach (RoslynStyleRuleOption roslynStyleRuleOption in roslynStyleRuleGroup.Options)
            {
                IDotnetConfigPropertySyntaxNode? editorConfigPropertyNode = TryFindOptionNode(propertyNodes, roslynStyleRuleOption);
                if (editorConfigPropertyNode is null)
                    continue;

                selectedStyleRuleNodes.Add(editorConfigPropertyNode);
            }

            if (roslynStyleRuleGroup.Rules.Any(r => r.RuleId.Equals(RoslynNameRuleInfo.RuleId)))
            {
                foreach (IDotnetConfigPropertySyntaxNode editorConfigPropertyNode in propertyNodes)
                {
                    if (editorConfigPropertyNode is not DotnetConfigRuleCompositeOptionNode option)
                        continue;

                    if (RoslynNameRuleInfo.IsNameRuleOption(option.ToFullString()))
                        selectedStyleRuleNodes.Add(editorConfigPropertyNode);
                }
            }
        }

        List<RoslynQualityRuleFormattedSection> formattedSections = new List<RoslynQualityRuleFormattedSection>();
        if (groupQualityRulesByCategory)
        {
            foreach (IGrouping<string, RoslynQualityRule> categoryRules in rules.QualityRules.GroupBy(r => r.Category).OrderBy(c => c.Key))
            {
                List<IDotnetConfigPropertySyntaxNode> selectedQualityRuleNodes = new List<IDotnetConfigPropertySyntaxNode>();
                foreach (RoslynQualityRule qualityRule in categoryRules.OrderBy(r => r.RuleId))
                {
                    IDotnetConfigPropertySyntaxNode? editorConfigPropertyNode = TryFindSeverityNode(propertyNodes, qualityRule.RuleId);
                    if (editorConfigPropertyNode is null)
                        continue;

                    selectedQualityRuleNodes.Add(editorConfigPropertyNode);
                }

                if (selectedQualityRuleNodes.Any())
                    formattedSections.Add(new RoslynQualityRuleFormattedSection($"CA {categoryRules.Key}", selectedQualityRuleNodes));
            }
        }
        else
        {
            List<IDotnetConfigPropertySyntaxNode> selectedQualityRuleNodes = new List<IDotnetConfigPropertySyntaxNode>();
            foreach (RoslynQualityRule qualityRule in rules.QualityRules)
            {
                IDotnetConfigPropertySyntaxNode? editorConfigPropertyNode = TryFindSeverityNode(propertyNodes, qualityRule.RuleId);
                if (editorConfigPropertyNode is null)
                    continue;

                selectedQualityRuleNodes.Add(editorConfigPropertyNode);
            }
            if (selectedQualityRuleNodes.Any())
                formattedSections.Add(new RoslynQualityRuleFormattedSection("CA", selectedQualityRuleNodes));
        }

        nodesForRemoving.AddRange(selectedStyleRuleNodes);
        nodesForRemoving.AddRange(formattedSections.SelectMany(s => s.SelectedQualityRuleNodes));
        DotnetConfigCategoryNode autoGeneratedSection = CreateAutoGeneratedCategory(selectedStyleRuleNodes, formattedSections);

        return document
            .RemoveNodes(nodesForRemoving)
            .AddChild(autoGeneratedSection);
    }

    public record RoslynQualityRuleFormattedSection(string Title, IReadOnlyCollection<IDotnetConfigPropertySyntaxNode> SelectedQualityRuleNodes);

    private DotnetConfigCategoryNode CreateAutoGeneratedCategory(
        IReadOnlyCollection<IDotnetConfigPropertySyntaxNode> styleRuleNodesForMoving,
        IReadOnlyCollection<RoslynQualityRuleFormattedSection> qualityRuleNodesForMoving)
    {
        var autoGeneratedSection = new DotnetConfigCategoryNode("*.cs", [], ["# Autogenerated values"], null);

        if (styleRuleNodesForMoving.Any())
        {
            var styleRuleSection = new DotnetConfigSectionNode("### IDE ###");

            foreach (IDotnetConfigPropertySyntaxNode styleRule in styleRuleNodesForMoving)
                styleRuleSection = styleRuleSection.AddChild(styleRule);

            autoGeneratedSection = autoGeneratedSection.AddChild(styleRuleSection);
        }

        foreach (RoslynQualityRuleFormattedSection roslynQualityRuleFormattedSection in qualityRuleNodesForMoving)
        {
            if (roslynQualityRuleFormattedSection.SelectedQualityRuleNodes.IsEmpty())
                continue;

            var qualitySection = new DotnetConfigSectionNode($"### {roslynQualityRuleFormattedSection.Title} ###");
            foreach (IDotnetConfigPropertySyntaxNode qualityRule in roslynQualityRuleFormattedSection.SelectedQualityRuleNodes)
                qualitySection = qualitySection.AddChild(qualityRule);
            autoGeneratedSection = autoGeneratedSection.AddChild(qualitySection);
        }

        return autoGeneratedSection;
    }

    private IReadOnlyCollection<IDotnetConfigPropertySyntaxNode> SelectIdeNodes(DotnetConfigDocument document, string ruleType)
    {
        List<IDotnetConfigPropertySyntaxNode> propertyNodes = document
            .DescendantNodes()
            .OfType<IDotnetConfigPropertySyntaxNode>()
            .ToList();

        List<IDotnetConfigPropertySyntaxNode> styleRuleNodes = new List<IDotnetConfigPropertySyntaxNode>();
        foreach (IDotnetConfigPropertySyntaxNode editorConfigPropertyNode in propertyNodes)
        {
            if (editorConfigPropertyNode is not DotnetConfigRuleSeverityNode severityConfigSetting)
                continue;

            if (severityConfigSetting.RuleId.RuleType == ruleType)
                styleRuleNodes.Add(editorConfigPropertyNode);
        }

        return styleRuleNodes;
    }

    private IDotnetConfigPropertySyntaxNode? TryFindSeverityNode(IReadOnlyCollection<IDotnetConfigPropertySyntaxNode> propertyNodes, RoslynRuleId id)
    {
        foreach (IDotnetConfigPropertySyntaxNode editorConfigPropertyNode in propertyNodes)
        {
            if (editorConfigPropertyNode is not DotnetConfigRuleSeverityNode severitySettings)
                continue;

            if (severitySettings.RuleId == id)
                return editorConfigPropertyNode;
        }

        return null;
    }

    private IDotnetConfigPropertySyntaxNode? TryFindOptionNode(IReadOnlyCollection<IDotnetConfigPropertySyntaxNode> propertyNodes, RoslynStyleRuleOption roslynStyleRuleOption)
    {
        foreach (IDotnetConfigPropertySyntaxNode editorConfigPropertyNode in propertyNodes)
        {
            if (editorConfigPropertyNode is not DotnetConfigRuleOptionNode option)
                continue;

            if (option.Key == roslynStyleRuleOption.Name)
                return editorConfigPropertyNode;
        }

        return null;
    }
}